/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logueo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public Ventana2() {
        initComponents();
        cargardatos();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        BTN_insert = new javax.swing.JButton();
        BTN_delet = new javax.swing.JButton();
        BTN_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre_proy");

        jLabel2.setText("Lider_proy");

        jLabel3.setText("Fecha_pres");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        BTN_insert.setText("Insertar");
        BTN_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_insertActionPerformed(evt);
            }
        });

        BTN_delet.setText("Borrar");
        BTN_delet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_deletActionPerformed(evt);
            }
        });

        BTN_exit.setText("Salir");
        BTN_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(BTN_insert)
                .addGap(46, 46, 46)
                .addComponent(BTN_delet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_exit)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_insert)
                    .addComponent(BTN_delet)
                    .addComponent(BTN_exit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void BTN_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_insertActionPerformed
       Connection con;
             java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ventana2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://129.159.108.161:3306/admin_default","admin_default","clase_luisrey");
             
            java.sql.Statement stmt;
            stmt = con.createStatement();
             JOptionPane.showMessageDialog(null, "Operacion realizada con exito!!!");
           
            String query="";
            query="insert into Integradores (lider_proy,nombre_proy,fecha_pre) values (";
            query = query+"'"+jTextField1.getText().toString()+"',";
            query = query+"'"+jTextField2.getText().toString()+"',";
            query = query+"'"+jTextField3.getText().toString()+"'";
            query = query+")";
           
            System.out.println(query);

            stmt.executeUpdate(query);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
           
            rs = stmt.executeQuery("select id,lider_proy , nombre_proy,fecha_pre from Integradores where estatus =1");

            rs.next();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("Lider Proy");
            modelo.addColumn("Nombre Proy");
            modelo.addColumn("Fecha_Pre");
           // jTable1.setModel(modelo);
            String filas [] = new String[4];

             do{                
               filas [0]=rs.getString("id");
               filas [1]=rs.getString("lider_proy");
               filas [2]=rs.getString("nombre_proy");
               filas [3]=rs.getString("fecha_pre");
               
               modelo.addRow(filas);

            } while(rs.next()==true);
         jTable1.setModel(modelo);

         // JOptionPane.showMessageDialog(null, "se conecto");
           

        } catch (SQLException ex) {
            Logger.getLogger(Ventana2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTN_insertActionPerformed

    private void BTN_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTN_exitActionPerformed

    private void BTN_deletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_deletActionPerformed
        if (jTable1.getSelectedRow()>=0){
      //  JOptionPane.showMessageDialog(null, "renglon seleccionado: "+jTable1.getSelectedRow());
      //  JOptionPane.showMessageDialog(null, "Total renglones: "+jTable1.getRowCount());
        System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
        System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());
        System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
         Connection con;
             java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ventana2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://129.159.108.161:3306/admin_default","admin_default","clase_luisrey");
             
            java.sql.Statement stmt;
            stmt = con.createStatement();
            // JOptionPane.showMessageDialog(null, "se ejecuto insert, revise!!!");
           
            String query="";
            query="update Integradores set estatus = 0 where id=";
            query = query+jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
           
            System.out.println(query);

            stmt.executeUpdate(query);
           
            rs = stmt.executeQuery("select id,lider_proy , nombre_proy,fecha_pre from Integradores where estatus =1");

            rs.next();
            DefaultTableModel modelo = new DefaultTableModel();
             modelo.addColumn("ID");
            modelo.addColumn("Nombre_Proy");
            modelo.addColumn("Lider_Proy");
            modelo.addColumn("Fecha_Pre");
           // jTable1.setModel(modelo);
            String filas [] = new String[4];

             do{                
               filas [0]=rs.getString("id");
               filas [1]=rs.getString("nombre_proy");
               filas [2]=rs.getString("lider_proy");
               filas [3]=rs.getString("fecha_pre");
               
               modelo.addRow(filas);

            } while(rs.next()==true);
         jTable1.setModel(modelo);

         // JOptionPane.showMessageDialog(null, "se conecto");
           

        } catch (SQLException ex) {
            Logger.getLogger(Ventana2.class.getName()).log(Level.SEVERE, null, ex);
        }
  }else{
      JOptionPane.showMessageDialog(null, "Debe seleccionar algo");
  }
    }//GEN-LAST:event_BTN_deletActionPerformed
    void cargardatos(){
        Connection con;
             java.sql.ResultSet rs;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Ventana2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con = DriverManager.getConnection("jdbc:mysql://129.159.108.161:3306/admin_default","admin_default","clase_luisrey");
             
            java.sql.Statement stmt;
            stmt = con.createStatement();
            rs=stmt.executeQuery("select id,nombre_proy ,lider_proy,fecha_pre from Integradores where estatus =1");
            rs.next();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("ID");
            modelo.addColumn("Lider_Proy");
            modelo.addColumn("Nombre_Proy");
            modelo.addColumn("Fecha_Pre");
           // jTable1.setModel(modelo);
            String filas [] = new String[4];

             do{                
               filas [0]=rs.getString("id");
               filas [1]=rs.getString("lider_proy");
               filas [2]=rs.getString("nombre_proy");
               filas [3]=rs.getString("fecha_pre");
               
               modelo.addRow(filas);

            } while(rs.next()==true);
         jTable1.setModel(modelo);

         // JOptionPane.showMessageDialog(null, "se conecto");
           

        } catch (SQLException ex) {
            Logger.getLogger(Ventana2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_delet;
    private javax.swing.JButton BTN_exit;
    private javax.swing.JButton BTN_insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
